name: Despliegue de Backend en AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1.- Checkout a la versión del código
      uses: actions/checkout@v4

    - name: 2.- Configurar agente ssh
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
